USE [master]
GO

/****** Object:  Database [StarMeAppDB]    Script Date: 8/22/2020 6:51:08 PM ******/
CREATE DATABASE [StarMeAppDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StarMeAppDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StarMeAppDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StarMeAppDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\StarMeAppDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StarMeAppDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StarMeAppDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StarMeAppDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StarMeAppDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StarMeAppDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StarMeAppDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [StarMeAppDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StarMeAppDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StarMeAppDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StarMeAppDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StarMeAppDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StarMeAppDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StarMeAppDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StarMeAppDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StarMeAppDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StarMeAppDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StarMeAppDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StarMeAppDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StarMeAppDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StarMeAppDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StarMeAppDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StarMeAppDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StarMeAppDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StarMeAppDB] SET RECOVERY FULL 
GO

ALTER DATABASE [StarMeAppDB] SET  MULTI_USER 
GO

ALTER DATABASE [StarMeAppDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StarMeAppDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StarMeAppDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StarMeAppDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StarMeAppDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StarMeAppDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StarMeAppDB] SET  READ_WRITE 
GO

